### ISSUE TITLE
Server/Host and Base Path configurations

### ISSUE THREAD

**Issue by JCooperElevateData** [temenos/APIs#1]
I am building an integration testing tool for all 400+ files not in archive. I noticed that in ~most cases, the default server/host and base parth configurations is incorrect. There are instances of the spec pointing to `localhost:8080` (and other ports) instead of `api.temenos.com`. I am using code generators for this project and while I can override the settings in the app, this should be corrected.

**Comment by temenos-labs** [comment]
Hi JCooper - thank you for this feedback. I think you might be running into the documented vs interactive element of our portal - all of the transact and financial crime mitigation APIs provide response data from the live sandbox (requiring the base URL of api.temenos.com and your API key), with the remainder intended for educational use only. Hope this helps - would like to see your project once complete :) [BenD]

**Comment by JCooperElevateData** [comment]
I hope to have an initial release out today. Currently everything is in an initial-build branch. I only have 37 of 400 sections to finish for the initial test suite. [OpenTemenos](https://github.com/ElevateData/OpenTemenos)

**Comment by temenos-labs** [comment]
Updated the readme [here](https://github.com/temenos/APIs/blob/master/README.md) - fcm and Transact are interactive as part of the multi-product sandbox. Will take me a little while to go through the rest of your feedback.

**Comment by JCooperElevateData** [comment]
If I understand correctly, each of these application (Transact/FCM/Datahub/ect) are all separately deployable applications and therefore can have separate base URLs. Also, since each app can be deployed separately, Some of the issues I am finding are only related to the sandbox and should not exist in production? If this is correct, I will split my library into multiple sections aligning with each application. That should make testing and deployment on my side much faster.

**Comment by temenos-labs** [comment]
Yes - the target url is consolidated for ease of access to external developers in the multi-product sandbox - in reality, it could point anywhere the application is deployed/load-balanced etc. I'm looking into those couple of API gateway issues today [BenD]
